# Python Review

Goals:
- recall basic python vocabulary
- practice markdown

## Libraries and packages
**library**: a collection of coade that we can use to perform specific tasks in our programs.

**NumPy**:
- core library for numerical computing in Python
- many other libraries use NumPy arrays as building blocks
- computations on NumPy are optimized for speed and memory usage

Let's impory NumPy with **standard abbreviation**

In [1]:
import numpy as np

## Variables

**variable**: a name we assign to a particular object in Python

Example:

In [2]:
# Assign a small array to a variable a
a = np.array([[1, 1, 2], [3, 5, 8]])

In [3]:
# Run a cell with the variable name to show value
a

array([[1, 1, 2],
       [3, 5, 8]])

In [4]:
# Use the `print` function to print the value
print(a)

[[1 1 2]
 [3 5 8]]


## Objects

**objects** (informally speaking) is a bundle of *properties* and *actions* about something specific.

Example:

Object: data frame

Properties: number rows, names of the columns, date created

Actions: selecting a specifc row, adding a new column

A variable is a the name we give a specific object, and the same object can be referenced by different variables

In practice, we can often use variable and object interchangeably.

## Types

Every object in Python has a **type**. The type tells us what kind of object it is.

We can also call the type of an object, the **class** of an object and they both mean what kind of object we have

In [5]:
print(a)

# Check the type/class of a variable/object by using `type` function
type(a)

[[1 1 2]
 [3 5 8]]


numpy.ndarray

In [6]:
# Indexing the value in the first row and first column
print(a[0,0])

# Check the type of an entry of the array by indexing
type(a[0,0])

1


numpy.int64

Notice that `type(a[0,0])` is `numpy.int64` and is not just the standard Python integer type. This is telling us that 1 is an integer stored as a 64-bit number.

In [10]:
print(a[1,1])

5


## Functions

`print` was our first example of a Python **function**.

Functions take in a set of **arguements** and those arguements creat an **output**.

arguement = parameter.

We can ask information about a function by executing `?function`

In [11]:
?print

Signature: print(*args, sep=' ', end='\n', file=None, flush=False)
Docstring:
Prints the values to a stream, or to sys.stdout by default.

sep
  string inserted between values, default a space.
end
  string appended after the last value, default a newline.
file
  a file-like object (stream); defaults to the current sys.stdout.
flush
  whether to forcibly flush the stream.
Type:      builtin_function_or_method

This information is a **docstring**.

A function has two types of arguements:

- **non-optional arguements**: arguements *you* need to specify for the function to do something
- **optional arguement**: arguements that are pre-filled with a default value by the function. You can override them. Optional arguements appear inside the parenthesis in the form `optional_arguement=default_value`

In [12]:
print('changing the default end arguement', end=' :)')

changing the default end arguement :)

## Attributed & methods

An object in Python has attributed and methods.

- **attribute**: a property of an object, some piece of information about it
- **method**: a procedure associated with the object, an action where the main ingredient is the object.

### Check-in

Fish attributes:

-length, color, species

Fish methods:

- die(), bite(), swim()

**Example**
Attributed for `numpy.arrays`

We can access a variable's attributed and methods by adding a period `.` at the end of the variable's name.

`variable.method()` or `variable.attribute`

In [13]:
a.shape

(2, 3)

In [14]:
type(a.shape)

tuple

In [15]:
# Methods examples
# min() returns the minimum value along a specified axis
a.min(axis=0)

array([1, 1, 2])

## Check-in

We can also call the `min` method without any parameters:

In [16]:
a.min() 

# This is an optional parameter, since the function works even if we don't specify the parameter

1

Remember: methods are functions associated with an object.

In [17]:
type(a.min)

builtin_function_or_method

## Exercise

1. Read the `print` function help. What is the type of the arguement `sep`? Is this an optional or non-optional arguemnet? Why?

2. Create two new variables, one with the integer value 77 and another one with the string 99.

3. Use your variables to print `77%99%77` by changing the value of one of the optional arguements in `print`.

In [18]:
?print

Signature: print(*args, sep=' ', end='\n', file=None, flush=False)
Docstring:
Prints the values to a stream, or to sys.stdout by default.

sep
  string inserted between values, default a space.
end
  string appended after the last value, default a newline.
file
  a file-like object (stream); defaults to the current sys.stdout.
flush
  whether to forcibly flush the stream.
Type:      builtin_function_or_method

The type of `sep` is a **string** (as noted in the documentation). It is also an **optional arguement** since if not given a string it will insert a space as the default.

In [19]:
j = 77
k = 99

In [23]:
print(j,k,j, sep='%')

77%99%77
